pipeline {
    agent any 
    stages {
        stage('Terraform init') { 
            steps {
                sh 'pwd && ls && terraform init -var accessKey=$AWS_ACCESS_KEY_ID -var secretKey=$AWS_SECRET_ACCESS_KEY '

            }
           }
        // stage('create 2 workspaces dev & prod') { 
        //     steps {
        //         sh 'terraform workspace new dev'
        //         sh 'terraform workspace new prod'

        //     }
        //    }
        stage('select dev workspace') { 
            steps {
                sh 'terraform workspace select dev'

            }
           }
           
            stage('Terraform apply') { 
            steps {
                sh 'terraform apply -var-file=dev.tfvars'

            }
           }
        }
    }
