pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                sh 'terraform init'
                sh 'terraform workspace new dev'
                sh 'terraform workspace new prod'
                sh 'terraform workspace select dev'
                sh 'terraform apply -var-file=dev.tfvars'

            }
           }
        }
    }
